add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " (bold green)"
error_symbol = " (bold red) "

[hostname]
ssh_only = true
# prefix = " "
disabled = false
style = "bold italic #FDFBFC"

[package]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "../"
style = "fg:21"

[username]
style_user = "bold italic #FDFBFC"
format = "[$user]($style) "
disabled = false
show_always = true

