# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
